apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-project
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://github.com/Cloud-Lucky/demo-backend-config.git
      path: argo
      targetRevision: main
    - repoURL: https://github.com/Cloud-Lucky/demo-frontend-config.git
      path: argo
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
